### ISSUE TITLE
Use records?

### ISSUE THREAD

**Issue by srpeirce** [ardalis/ValueObjectsDemo#2]
Sorry for the unsolicited issue - I follow you on GitHub and saw your repo in my feed :P

My *guess* you are looking at ValueObject example in relation to DDD - I was curious if you have considered records?

Best,
Steve

**Comment by ardalis** [comment]
Yeah I need to link to the article this goes with. It's at https://ardalis.com/blog

I talk about records there. Short version is the with keyword that lets you create records from other records without going through the constructor breaks things.

**Comment by srpeirce** [comment]
@ardalis thanks for response. I think that you can work around that by setting an explicit constructor and properties with `private init`. Take a look and see what you think, it might be that I'm missing something.

All the best,
Another Steve

![image](https://user-images.githubusercontent.com/12847647/132769905-ab642922-968e-4fd2-b014-fe58e921c596.png)

```csharp
using System;

var steve1 = new Title("Steve");
var steve2 = new Title("Steve");

Console.WriteLine($"steve1: {steve1}"); // Output: steve1: Title { Name = Steve }
Console.WriteLine($"steve2: {steve2}");  //Output: steve2: Title { Name = Steve }
Console.WriteLine($"steve1 ==  steve2? {steve1 == steve2}"); // Output: steve1 ==  steve2? True

Console.WriteLine($"{Environment.NewLine}");

var shoutySteve1 = steve1.ToShouty();
Console.WriteLine($"steve1: {steve1}"); // Output: steve1: Title { Name = Steve }
Console.WriteLine($"shoutySteve1: {shoutySteve1}"); // Output: shoutySteve1: Title { Name = STEVE }
Console.WriteLine($"steve1 == shoutySteve1? {steve1 == shoutySteve1}"); // Output: steve1 ==  shoutySteve1? False

//var shoutySteve2 = steve2 with { Name = Name.ToUpper() };

public record Title
{
    public string Name { get; private init; }

    public Title(string name)
    {
        Name = name;
    }

    public Title ToShouty() => this with { Name = Name.ToUpper() };
}
```

**Comment by srpeirce** [comment]
I think this is more or less equivalent to your Address class. (You probably don't need the `private init;` accessor in this case)

````csharp
namespace ValueObjects.Console.Model2;

public record Address
{
    public string Address1 { get; private init; }
    public string? Address2 { get; private init; }
    public string City { get; private init; }
    public string State { get; private init; }
    public string PostalCode { get; private init; }
    public string Country { get; private init; }

    public Address(string address1, string city, string state,
        string postalCode, string country, string? address2 = null)
    {
        Address1 = address1;
        City = city;
        State = state;
        PostalCode = postalCode;
        Country = country;
        Address2 = address2;
    }
}
```

**Comment by Arnab-Developer** [comment]
Looking into [this post](https://enterprisecraftsmanship.com/posts/csharp-records-value-objects/) I think not only `with` keyword but there are other reasons of not using `records` for value types in DDD.

**Comment by ardalis** [comment]
Thanks, @Arnab-Developer. Those are exactly the reasons, including the example of using `with` to bypass logic in the constructor.

**Comment by srpeirce** [comment]
I'm not following - you mean changing the equality overrides? You can do that too! 

If not, what other limitation are you referring?

```csharp
using System;

var steve1 = new Title("Steve");
var steve2 = new Title("Steve");

Console.WriteLine($"steve1: {steve1}"); // Output: steve1: Title { Name = Steve }
Console.WriteLine($"steve2: {steve2}");  //Output: steve2: Title { Name = Steve }
Console.WriteLine($"steve1 ==  steve2? {steve1 == steve2}"); // Output: steve1 ==  steve2? True

Console.WriteLine($"{Environment.NewLine}");

var shoutySteve1 = steve1.ToShouty();
Console.WriteLine($"steve1: {steve1}"); // Output: steve1: Title { Name = Steve }
Console.WriteLine($"shoutySteve1: {shoutySteve1}"); // Output: shoutySteve1: Title { Name = STEVE }
Console.WriteLine($"steve1 == shoutySteve1? {steve1 == shoutySteve1}"); // Output: steve1 ==  shoutySteve1? True -- Overridden Equals
Console.WriteLine($"steve1.Equals(shoutySteve1)? {steve1.Equals(shoutySteve1)}"); // Output: steve1.Equals(shoutySteve1)? True -- Overridden Equals

//var shoutySteve2 = steve2 with { Name = Name.ToUpper() }; // can't do this as private init property

public record Title
{
    public string Name { get; private init; }

    public Title(string name)
    {
        Name = name;
    }

    public Title ToShouty() => this with { Name = Name.ToUpper() };

    public virtual bool Equals(Title? other)
    {
        return Name.Equals(other?.Name, StringComparison.InvariantCultureIgnoreCase);
    }

    public override int GetHashCode()
    {
        return (Name != null ? Name.GetHashCode() : 0);
    }
}
```

**Comment by Arnab-Developer** [comment]
Got your point. But as an example, what about point number 6 in [this](https://enterprisecraftsmanship.com/posts/csharp-records-value-objects/) document?

**Comment by srpeirce** [comment]
> Got your point. But as an example, what about point number 6 in [this](https://enterprisecraftsmanship.com/posts/csharp-records-value-objects/) document?

This is achievable with records also. 

I typed this on my phone so please excuse any syntax issues:


```csharp

public abstract record ValueObject;

public sealed record Title : ValueObject 
{
    public Title(string name) 
    {
        Name = name;
    }

    public string Name { get; private init;} 

    public Title ToShouty() => this with { Name: Name. ToUpper() } 
} 
```

**Comment by Arnab-Developer** [comment]
May be we can use `record` for ValueObjects. But I think the point here is, if we write `record` like a `class` by inheriting `ValueObject` and overriding `GetEqualityComponents` method in it then what is the point to create a `record` it is better to create a `class`?

**Comment by srpeirce** [comment]
I'm a huge fan of Kiss principle and using idiomatic code.

Imo records already have a lot of behaviour that we are looking for inside a value object:
- Immutability
- Equality Operators

You are using the existing language constructs without a dependency on a third party library, or writing your own base classes.

You have additional power such as the `with` keyword that you can use in your methods without exposing publicly - for value objects this is awesome and saves a lot of code. 

I suspect that 90% of value objects will not require custom equality checks, but there is a way to customise them if you need.

---

For me the biggest drawback is that you might make a mistake and allow the `with` operator externally (and tbf that might be fine in a lot of cases if there aren't specific invariance rules). 

For me this drawback is a worthwhile trade off on simplicity of code, but I accept this is an opinion - I'm always happy for people to disagree and I often change my mind on things haha.

**Comment by Arnab-Developer** [comment]
👍🏼 I got your point. Let's see what @ardalis thinks about it.

**Comment by srpeirce** [comment]
It's an option to consider at the very least 👍

**Comment by Arnab-Developer** [comment]
I checked the [details of `ValueObject` discussion](https://enterprisecraftsmanship.com/posts/value-object-better-implementation).

`ValueObject` abstract class code:

```csharp
public abstract class ValueObject
{
    protected abstract IEnumerable<object> GetEqualityComponents();

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;

        if (GetType() != obj.GetType())
            return false;

        var valueObject = (ValueObject)obj;

        return GetEqualityComponents().SequenceEqual(valueObject.GetEqualityComponents());
    }

    public override int GetHashCode()
    {
        return GetEqualityComponents()
            .Aggregate(1, (current, obj) =>
            {
                unchecked
                {
                    return current * 23 + (obj?.GetHashCode() ?? 0);
                }
            });
    }

    public static bool operator ==(ValueObject a, ValueObject b)
    {
        if (ReferenceEquals(a, null) && ReferenceEquals(b, null))
            return true;

        if (ReferenceEquals(a, null) || ReferenceEquals(b, null))
            return false;

        return a.Equals(b);
    }

    public static bool operator !=(ValueObject a, ValueObject b)
    {
        return !(a == b);
    }
}
```

The usage:

```csharp
public class Address : ValueObject
{
    public string Street { get; }
    public string City { get; }
    public string ZipCode { get; }

    public Address(string street, string city, string zipCode)
    {
        Street = street;
        City = city;
        ZipCode = zipCode;
    }

    protected override IEnumerable<object> GetEqualityComponents()
    {
        yield return Street;
        yield return City;
        yield return ZipCode;
    }
}
```

If we convert the `ValueObject` and `Address` to `record` then we can't customize the way it check equality if needed. Because `record` already have a built in equality check and we can't customize that.

![image](https://user-images.githubusercontent.com/3396447/132956112-4724f27e-3c92-47f0-b36e-a7c35c6454de.png)

[Characteristics of records](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records#characteristics-of-records)

I agree with you on the point, where you don't need customization on the features what `record` does automatically then you should use `record`. This point also there in [the document](https://enterprisecraftsmanship.com/posts/csharp-records-value-objects/) (at the end).

**Comment by srpeirce** [comment]
> then we can't customize the way it check equality if needed. Because record already have a built in equality check and we can't customize that.

If you really need to you can, I think 1 of the examples above demonstrates this. It does mean writing your own code rather than `yield return` the values to compare. You should also override `GetHashCode() `. But in reality, how often would you need to do this? 

I expect only very few scenarios/domains would the default behaviour not make sense.

**Comment by vkhorikov** [comment]
My 2 cents. I agree that most projects don't need equality customization. To me, the biggest drawback of C# records is the lack of encapsulation (point #7 in the article). In order to encapsulate them properly, you'd need to introduce custom constructors and/or factory methods, which defeats the main benefit of records -- their conciseness.

This is similar to the use of .NET value types as value objects: https://enterprisecraftsmanship.com/posts/net-value-type-ddd-value-object/

**Comment by srpeirce** [comment]
Yerr it would be nice if you could initialise to effectively say that properties are `private init;` instead of having to be explicit.

That said, it's still less verbose.
```csharp
public class Address : ValueObject
{
    public string Street { get; }
    public string City { get; }
    public string ZipCode { get; }

    public Address(string street, string city, string zipCode)
    {
        Street = street;
        City = city;
        ZipCode = zipCode;
    }

    protected override IEnumerable<object> GetEqualityComponents()
    {
        yield return Street;
        yield return City;
        yield return ZipCode;
    }
}
```

That would be a 1 liner. 
```csharp
public record Address(string Street, string City, string ZipCode);
```

Why stop the `with` in this case? We don't do any sort of checks in constructor. 
If we did have a reason to block the `with` (e.g. if there was a Monetary amount it would not make sense to change the currency but keep the amount the same), it's still fewer lines of code. 
I'll stick to the address for consistency:

```csharp
public record Address(string Street, string City, string ZipCode)
{
    public string Street { get; } = Street;
    public string City { get; } = City;
    public string ZipCode { get; } = ZipCode;
}
```

![image](https://user-images.githubusercontent.com/12847647/132959458-152febc1-2b80-4e1f-924f-3defafb3571d.png)
![image](https://user-images.githubusercontent.com/12847647/132959463-66e70ade-31e0-4d25-a045-94bc13ea187e.png)

**Comment by ardalis** [comment]
Hmm, that's a neat trick. You just killed the `with` keyword by initializing all of the get-only properties to... themselves? Or more likely to the record arguments sharing the same names? I've never seen that syntax before or its effect, I must admit.

**Comment by Arnab-Developer** [comment]
I agree with the fact that most of the points in [this document](https://enterprisecraftsmanship.com/posts/csharp-records-value-objects) can be done with `record`. 

But I think author choose to use `class` to implement custom equality logic and encapsulation logic (with private constructor and factory method) and not `record` because if we write a `record` and put private constructor inside that and override `Equals` method in that then we are not using some of the built in features of `record` so may be for that reason author choose `class` over `record` in this case.

**Comment by Arnab-Developer** [comment]
As an example:

We can do this with `record`.

```csharp
using static System.Console;

Person p1 = new(1, "Jon");
Person p2 = p1 with { Name = "Bob" };

WriteLine(p1);
WriteLine(p2);

record Person(int Id, string Name);
```

But if we want encapsulation then we need to do this.

```csharp
using static System.Console;

Person p1 = Person.Create(1, "Jon");
Person p2 = p1 with { Name = "Bob" }; // compilation error

WriteLine(p1);
WriteLine(p2);

record Person
{
    public int Id { get; private set; }
    public string Name { get; private set; }
    
    private Person(int id, string name)
    {
        Id = id;
        Name = name;
    }

    public static Person Create(int id, string name)
    {
        return new Person(id, name);
    }
}
```

In this case we can achieve encapsulation with `record` but if we can't use `with` then what is the point to use a `record`? It is better to use `class` in this case.

**Comment by srpeirce** [comment]
Hello, the `with` keyword is just 1 feature of records to aid with Immutability. 
You might stop this from `public` scope, but you could still use it privately. E.g. My example in a comment above. This can keep code cleaner and intention revealing. 

As mentioned, you get default equality checking behaviour, and a nicely formatted `ToString()`. You also get things like a deconstructor for free. 

You can achieve the behaviour with a normal class or record, my proposal is to experiment with the code and see what code you feel is cleaner and more intention revealing. Having some solid tests will help too, meaning you can change your mind with confidence. 

----
If the code above was a PR I would probably ask some questions along the lines:

* Given your constructor method takes the same arguments as the constructor, "is the code simpler to just use the constructor"? I understand why you have done this, but I like KISS
* I expect the intention of the record is to be immutable, have you considered `private init;` property accessory instead of `private set;`
  * Potentially omitting the Set altogether if no intention to use the `with keyword`. 


Side note: the fact that there is an ID implies the intent here is an entity as opposed to a value object.

**Comment by Arnab-Developer** [comment]
Most of the points in [this document](https://enterprisecraftsmanship.com/posts/csharp-records-value-objects) can be done with `record`. If we try to convert the `ValueObject` example with `record`, it becomes something like below (excuse me if the code is not great in quality because it is just an example).

```csharp
using System;
using System.Linq;
using static System.Console;

Address a1 = Address.Create("st1", "zip1");
Address a2 = Address.Create("st1", "zip2");
WriteLine(a1 == a2);
Address[] addresses = new[] { a1, a2 }.OrderBy(x => x).ToArray();
foreach (Address add in addresses)
{
    WriteLine(add);
}

abstract record ValueObject
{
}

record Address : ValueObject, IComparable
{
    public string Street { get; }
    public string ZipCode { get; }

    private Address(string street, string zipCode)
    {
        Street = street;
        ZipCode = zipCode;
    }

    public static Address Create(string street, string zipCode) => new Address(street, zipCode);

    public int CompareTo(object? obj)
    {
        if (obj is null) throw new ArgumentNullException(nameof(obj));
        Address a = (Address)obj;
        if (Street == a.Street) return 0;
        else if (Street.Length > a.Street.Length) return 1;
        else return -1;
    }

    public virtual bool Equals(Address? a) => a is not null && Street == a.Street;

    public override int GetHashCode() => Street.GetHashCode();
}
```

There are two way of thinking here:

- If we need to implement interface, create factory method, private constructor, override Equals method in a `record` then we are not using some features which automatically `record` provides. So it is better to use a `class` in this case.
- It is true that we need to implement interface, create factory method, private constructor, override Equals method in a `record` but there are other features of `record` which we can use like it automatically overrides `==` and `!=` operator and `ToString` method for nice printable object data. So let's continue with `record`.

Which option we should take is a personal preference.

**Comment by ardalis** [comment]
This is a good discussion and has good points on both sides. I like @Arnab-Developer 's summary in the last comment. To me, if I'm going to use records to represent value objects, I don't want to have to jump through major hoops to make them work. And by major hoops I mean custom equality and static factory methods just to achieve the same encapsulation I get from classes. As @vkhorikov pointed out, once you have to do all that the main benefit of records - their succinctness - is gone.

So, my plan at least for now is to stick with classes and probably VK's base Value Object or something close to it. If in the future the C# team provides a way of easily disabling the use of the `with` keyword (or at least only allowing its use privately, which I think would be fine), and potentially also custom equality (though this is less critical IMO) I would reconsider.

**Comment by srpeirce** [comment]
It's a nice conversation. 

I'm still not sure that I'm aligned with the summary comment, but I'm happy to disagree and it's good to think. For me 99% cases that require ValueObjects can be achieved with cleaner code as per this comment 
* Add a few properties
* Does not require equality and static factory methods.

https://github.com/ardalis/ValueObjectsDemo/issues/2#issuecomment-917465659

It would be nice for them to support this without the additional properties...can see if it is on the language backlog (else a possible feature request).

**Comment by nhwilly** [comment]
I know this thread is old, but what about serialization?  I get errors when I try to serialize/deserialize value objects.  Seems like I need a converter or something.  And then there's the problem of projects where NewtonSoft and System.Text.Json are mixed.
